# API ключи
OPENROUTER_API_KEY = "Ключ OpenRouter"

# URL сервисов (можно также указать здесь)
COMFYUI_URL = "ссылка на ComfyUI" # или http://localhost:8188 и http://localhost:8000
FOLDER_ID = "ID папки с моделями на Google Disk" # 1t31ah2uXrnzqxt-e3Fi_qij6ftt9OImy - для ahi, "12uIn6C6m56o9QmPyfxTGM85NsvnS5T-S" - для grun

OLLAMA_URL = "ссылка на локальную VLLM"

# Модели
OPENROUTER_MODEL = "название модели в OpenRouter"
OLLAMA_MODEL = "название локальной VLLM"

# Настройки workflow
DREAMSHAPER_WORKFLOW = "путь к workflow для генерации картинок"
HYNUAN3D_WORKFLOW = "путь к workflow для генерации моделей"

# Лимиты и настройки
MAX_IMAGE_SIZE_MB = 10
TIMEOUT_GENERATION = 750
TIMEOUT_3D = 120

# Google Drive URL для модели
MODEL_GDRIVE_URL = "ссылка на GDrive"